### ISSUE TITLE
Config inconsistent after `eltf_freeze`

### ISSUE THREAD

**Issue by bedapisl** [iterait/emloop-tensorflow#31]
`eltf_freeze` script changes `model.class` to `emloop_tensorflow.FrozenModel` but `model.restore_fallback` is not changed and remains `emloop_tensorflow.BaseModel` which leads to wrong config.
Example `config.yaml`:
```
model:
  class: emloop_tensorflow.FrozenModel

  ...

  restore_fallback: emloop_tensorflow.BaseModel
```
